steps:

- name: 'gcr.io/cloud-builders/git'
  id: Write Datafix branch
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    podname=$(echo ${_HEAD_BRANCH} | tr '[:upper:]' '[:lower:]')
    echo $podname
    sed -i "s/BRANCH_NAME/$podname/g" manifests/pod.yaml

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=manifests/
  - --location=europe-west1
  - --namespace=${_NAMESPACE}
  - --cluster=${PROJECT_ID}-cluster
  timeout: 600s
