steps:

- name: 'gcr.io/cloud-builders/git'
  id: Write environment config
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    sed "s/BASE_URL_VALUE/${_BASE_URL}/g" docker/env.json
    sed "s/API_KEY_VALUE/${_API_KEY}/g" docker/env.json
    sed "s/CLIENT_ID_VALUE/${_CLIENT_ID}/g" docker/env.json
    sed "s/CLIENT_SECRET_VALUE/${_CLIENT_SECRET}/g" docker/env.json
    sed "s/CALLBACK_URL_VALUE/${_CALLBACK_URL}/g" docker/env.json
    sed "s/ID_TOKEN_VALUE/${_ID_TOKEN}/g" docker/env.json


- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '--build-arg'
  - 'version=$SHORT_SHA'
  - '-t'
  - 'europe-docker.pkg.dev/dft-rsss-findtransptdata-dev/dft-nap/postmanrunner:$SHORT_SHA'
  - '.'
  - '-f'
  - docker/Dockerfile
  timeout: 660s

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'europe-docker.pkg.dev/dft-rsss-findtransptdata-dev/dft-nap/postmanrunner:$SHORT_SHA'

